### PR TITLE
fix: allow slot assignment for single-node clusters (#131)

### LINKED ISSUE #131: Operator is stuck at `slots are not assigned, requeue..` if the cluster have 1 shard, 0 replica
when creating a Valkey cluster with the following CR, the reconciliation function will keep repeating the check for unassigned slots loop:
```yaml
apiVersion: valkey.io/v1alpha1
kind: ValkeyCluster
metadata:
  name: no-exporter
spec:
  shards: 1
  replicas: 0
  exporter:
    enabled: false
```

Operator log:
```
2026-04-09T04:22:11Z    DEBUG   reconcile...    {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "21da6899-0e2a-44a3-a233-d0c40bad9f29"}
2026-04-09T04:22:11Z    DEBUG   internal ACLs unchanged {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "21da6899-0e2a-44a3-a233-d0c40bad9f29"}
2026-04-09T04:22:11Z    DEBUG   slots are not assigned, requeue..       {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "21da6899-0e2a-44a3-a233-d0c40bad9f29", "unassignedSlots": [{"Start":0,"End":16383}]}
2026-04-09T04:22:13Z    DEBUG   reconcile...    {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "25ddac3d-2eb1-4032-ae07-8a7767e7a842"}
2026-04-09T04:22:13Z    DEBUG   internal ACLs unchanged {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "25ddac3d-2eb1-4032-ae07-8a7767e7a842"}
2026-04-09T04:22:13Z    DEBUG   slots are not assigned, requeue..       {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "25ddac3d-2eb1-4032-ae07-8a7767e7a842", "unassignedSlots": [{"Start":0,"End":16383}]}
2026-04-09T04:22:15Z    DEBUG   reconcile...    {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "9baa0b13-b2ea-4494-a697-3610196f39de"}
<repeating ad infinitum>
```

If you create the cluster with > 1 shard, then later scale it down to 1, the operator will still work:
```bash
cat <<EOF |kubectl apply -f -
apiVersion: valkey.io/v1alpha1
kind: ValkeyCluster
metadata:
  name: no-exporter
spec:
  shards: 2
  replicas: 0
  exporter:
    enabled: false
EOF
```

```
2026-04-09T04:25:29Z    DEBUG   events  Cluster ready with 2 shards and 0 replicas      {"type": "Normal", "object": "nil", "action": "ReconcileCluster", "reason": "ClusterReady"}
```

```bash
cat <<EOF |kubectl apply -f -
apiVersion: valkey.io/v1alpha1
kind: ValkeyCluster
metadata:
  name: no-exporter
spec:
  shards: 1
  replicas: 0
  exporter:
    enabled: false
EOF
```

```
2026-04-09T04:26:50Z    DEBUG   draining slots  {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "dcae5466-5131-45d8-ba81-948d2b1f52fd", "src": "10.244.0.10", "dst": "10.244.0.9", "slots": 192}
2026-04-09T04:26:50Z    DEBUG   events  Moving 192 slots from 10.244.0.10 to 10.244.0.9 {"type": "Normal", "object": "nil", "action": "ScaleIn", "reason": "SlotsDraining"}
2026-04-09T04:26:52Z    DEBUG   reconcile...    {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "1c99f11e-9ee5-4192-b2d0-414271996772"}
2026-04-09T04:26:52Z    DEBUG   internal ACLs unchanged {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "1c99f11e-9ee5-4192-b2d0-414271996772"}
2026-04-09T04:26:52Z    DEBUG   reconciling ValkeyNode  {"controller": "valkeynode", "controllerGroup": "valkey.io", "controllerKind": "ValkeyNode", "ValkeyNode": {"name":"no-exporter-1-0","namespace":"default"}, "namespace": "default", "name": "no-exporter-1-0", "reconcileID": "1cb6a575-51da-4ace-a9eb-73476c92aeae"}
2026-04-09T04:26:52Z    DEBUG   deleted excess ValkeyNode       {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "1c99f11e-9ee5-4192-b2d0-414271996772", "name": "no-exporter-1-0", "shard": 1, "node": 0}
2026-04-09T04:26:52Z    DEBUG   events  Deleted excess ValkeyNode no-exporter-1-0 (shard 1, node 0)     {"type": "Normal", "object": "nil", "action": "ScaleIn", "reason": "ValkeyNodeDeleted"}
2026-04-09T04:26:52Z    DEBUG   reconcile...    {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "6ee21c87-63b8-4916-a69d-39507ffd54c1"}
2026-04-09T04:26:52Z    DEBUG   internal ACLs unchanged {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "6ee21c87-63b8-4916-a69d-39507ffd54c1"}
2026-04-09T04:26:52Z    DEBUG   events  Cluster ready with 1 shards and 0 replicas      {"type": "Normal", "object": "nil", "action": "ReconcileCluster", "reason": "ClusterReady"}
```

### PR DESCRIPTION
**Pull request by daanvinken**
This PR closes #131

### Summary
A `ValkeyCluster` with 1 shard and 0 replicas gets stuck in an infinite reconciliation loop because `assignSlotsToPendingPrimaries()` skips isolated nodes, and a single-node cluster is permanently isolated with no peer to MEET.
This causes an infinite reconciliation loop 
```
2026-04-09T04:22:11Z    DEBUG   reconcile...    {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "21da6899-0e2a-44a3-a233-d0c40bad9f29"}
2026-04-09T04:22:11Z    DEBUG   internal ACLs unchanged {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "21da6899-0e2a-44a3-a233-d0c40bad9f29"}
2026-04-09T04:22:11Z    DEBUG   slots are not assigned, requeue..       {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "21da6899-0e2a-44a3-a233-d0c40bad9f29", "unassignedSlots": [{"Start":0,"End":16383}]}
2026-04-09T04:22:13Z    DEBUG   reconcile...    {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "25ddac3d-2eb1-4032-ae07-8a7767e7a842"}
2026-04-09T04:22:13Z    DEBUG   internal ACLs unchanged {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "25ddac3d-2eb1-4032-ae07-8a7767e7a842"}
2026-04-09T04:22:13Z    DEBUG   slots are not assigned, requeue..       {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "25ddac3d-2eb1-4032-ae07-8a7767e7a842", "unassignedSlots": [{"Start":0,"End":16383}]}
2026-04-09T04:22:15Z    DEBUG   reconcile...    {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"no-exporter","namespace":"default"}, "namespace": "default", "name": "no-exporter", "reconcileID": "9baa0b13-b2ea-4494-a697-3610196f39de"}
<repeating ad infinitum>
```

It seems there's a deadlock between `meetIsolatedNodes()` and `assignSlotsToPendingPrimaries()`

When a single node starts up with `cluster_known_nodes = 1`, it's considered "isolated".

1. [`meetIsolatedNodes()`](https://github.com/valkey-io/valkey-operator/blob/5b9adec/internal/controller/valkeycluster_controller.go#L611-L613) picks a meet target via `findMeetTarget()`. Since there are no non-isolated nodes, it falls back to `isolated[0]` aka the only
   node. Then because `meetTarget == isolated[0]`, the node is removed from the list. The loop iterates over an empty slice, where no MEET is issued at any point in time.

2. [`assignSlotsToPendingPrimaries()`](https://github.com/valkey-io/valkey-operator/blob/5b9adec/internal/controller/valkeycluster_controller.go#L658-L659) skips isolated nodes (`cluster_known_nodes <= 1`). Since no MEET happened, `cluster_known_nodes` is still 1, the
   node is skipped and no slots are assigned.

3. The reconciler sees unassigned slots and requeues forever.

IIUC the isolation guard exists to prevent a pod in a multi-node cluster from getting slots before it's been introduced to its peers. But in a single-node cluster (1 shard, 0 replicas), isolation is the permanent correct state, there's no other node to MEET.

### Implementation

I considered fixing this in `meetIsolatedNodes()` itself, but that's a dead end.Even if we made the single node attempt to MEET itself, `CLUSTER MEET` with your own address is a no-op so that wouldn't help.

The simpler fix is in `assignSlotsToPendingPrimaries()`. If the whole cluster is one node, isolation is the correct permanent state and there's nothing to protect against.

### Testing

- E2e test added for single-shard zero-replica cluster creation, validating the cluster reaches Ready with all 16384 slots assigned 
- Tested locally (with an E2E as well), reloaded a new image with the fix while having reproduced the initial bug and the single node cluster came up:
```
 ༼ つ ▀_▀ ༽つ  ~  src  valkey-ope  k get valkeycluster                                                                                                                                       fix/single-shard-slot-assignment  3✎  2+  ⎈ kind-valkey-repro  22:19:07
NAME          STATE         REASON        AGE
single-node   Reconciling   Reconciling   10m
 ༼ つ ▀_▀ ༽つ  ~  src  valkey-ope  k get valkeycluster                                                                                                                                       fix/single-shard-slot-assignment  3✎  2+  ⎈ kind-valkey-repro  22:19:30
NAME          STATE   REASON           AGE
single-node   Ready   ClusterHealthy   10m
```

### CODE REVIEW

**Comment by jdheyburn** [comment]
Just a thought, would users want to have 1 shard (primary) with 1 replica, and expand out from there? What would we need to change in the code to support this case too, alongside 1 shard with 0 replica?

**Comment by daanvinken** [comment]
In that case there would be 2 nodes so that already works 👍

File: test/e2e/valkeycluster_test.go [hunk 1]
```diff
@@ -328,6 +328,85 @@ var _ = Describe("ValkeyCluster", Ordered, func() {
...
+				output, err := utils.Run(cmd)
+				g.Expect(err).NotTo(HaveOccurred())
+
+				cmd = exec.Command("kubectl", "delete", "pod", "client",
+					"--wait=true", "--timeout=30s")
+				_, err = utils.Run(cmd)
+				g.Expect(err).NotTo(HaveOccurred())
+
+				g.Expect(output).To(ContainSubstring("cluster_state:ok"))
+				g.Expect(output).To(ContainSubstring("cluster_slots_assigned:16384"))
```
Comment (bjosv) [inline test/e2e/valkeycluster_test.go:405]: Since we check both for ok and slots assigned we could also make sure `cluster_size:1`

**Review by bjosv — DISMISSED** [review]
Nice finding!

File: test/e2e/valkeycluster_test.go (hunk 1 above)
Comment (daanvinken) [reply test/e2e/valkeycluster_test.go:405]: Yeah good call, fixed!

**Comment by jdheyburn** [comment]
@daanvinken I did some testing locally, and I went from 1 shard 0 replicas to 1 shard 1 replica, and the replica was not able to join. 

```
2026-04-22T08:55:55Z    DEBUG   events  Shard has 1 of 2 nodes  {"type": "Normal", "object": "nil", "action": "CheckReplicas", "reason": "WaitingForReplicas"}
2026-04-22T08:55:56Z    DEBUG   reconciling ValkeyNode  {"controller": "valkeynode", "controllerGroup": "valkey.io", "controllerKind": "ValkeyNode", "ValkeyNode": {"name":"cluster-sample-0-0","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample-0-0", "reconcileID": "d10901ca-b123-414c-b1c3-4cb1acf4ec4b"}
2026-04-22T08:55:56Z    DEBUG   getting internal secret {"controller": "valkeynode", "controllerGroup": "valkey.io", "controllerKind": "ValkeyNode", "ValkeyNode": {"name":"cluster-sample-0-0","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample-0-0", "reconcileID": "d10901ca-b123-414c-b1c3-4cb1acf4ec4b", "node-labels": {"app.kubernetes.io/component":"valkey-node","app.kubernetes.io/instance":"cluster-sample-0-0","app.kubernetes.io/managed-by":"valkey-operator","app.kubernetes.io/name":"valkey","app.kubernetes.io/part-of":"valkey","valkey.io/cluster":"cluster-sample","valkey.io/node-index":"0","valkey.io/shard-index":"0"}}
2026-04-22T08:55:56Z    DEBUG   reconciled StatefulSet  {"controller": "valkeynode", "controllerGroup": "valkey.io", "controllerKind": "ValkeyNode", "ValkeyNode": {"name":"cluster-sample-0-0","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample-0-0", "reconcileID": "d10901ca-b123-414c-b1c3-4cb1acf4ec4b", "result": "updated", "name": "valkey-cluster-sample-0-0"}
2026-04-22T08:55:56Z    DEBUG   ValkeyNode reconciliation complete      {"controller": "valkeynode", "controllerGroup": "valkey.io", "controllerKind": "ValkeyNode", "ValkeyNode": {"name":"cluster-sample-0-0","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample-0-0", "reconcileID": "d10901ca-b123-414c-b1c3-4cb1acf4ec4b"}
2026-04-22T08:55:57Z    DEBUG   reconcile...    {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"cluster-sample","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample", "reconcileID": "adfeab31-49c8-4d77-8fab-2116d6e682d8"}
2026-04-22T08:55:57Z    INFO    getting system users secret: cluster-sample     {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"cluster-sample","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample", "reconcileID": "adfeab31-49c8-4d77-8fab-2116d6e682d8"}
2026-04-22T08:55:57Z    DEBUG   internal ACLs unchanged {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"cluster-sample","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample", "reconcileID": "adfeab31-49c8-4d77-8fab-2116d6e682d8"}
2026-04-22T08:55:57Z    DEBUG   add a new replica       {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"cluster-sample","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample", "reconcileID": "adfeab31-49c8-4d77-8fab-2116d6e682d8", "primary IP": "10.244.0.28", "primary Id": "f87d4b87c3b1ec18f8e67a695b9adf36f4bfc708", "replica address": "10.244.0.29", "shardIndex": 0}
2026-04-22T08:55:57Z    DEBUG   replica does not yet know primary (gossip pending); will retry  {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"cluster-sample","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample", "reconcileID": "adfeab31-49c8-4d77-8fab-2116d6e682d8", "replica": "10.244.0.29", "primaryId": "f87d4b87c3b1ec18f8e67a695b9adf36f4bfc708"}
2026-04-22T08:55:57Z    DEBUG   skipping replica; primary not ready yet {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"cluster-sample","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample", "reconcileID": "adfeab31-49c8-4d77-8fab-2116d6e682d8", "node": "10.244.0.29", "shard": 0}
2026-04-22T08:55:57Z    DEBUG   missing replicas, requeue..     {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"cluster-sample","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample", "reconcileID": "adfeab31-49c8-4d77-8fab-2116d6e682d8"}
2026-04-22T08:55:57Z    DEBUG   events  Shard has 1 of 2 nodes  {"type": "Normal", "object": "nil", "action": "CheckReplicas", "reason": "WaitingForReplicas"}
```

Also I went from 1 shard 0 replicas to 2 shards 0 replicas, and the second shard was not able to join.

```
026-04-22T09:00:13Z    DEBUG   events  Waiting for 10.244.0.30 to learn node 10.244.0.31       {"type": "Normal", "object": "nil", "action": "RebalanceSlots", "reason": "SlotsRebalancePending"}
2026-04-22T09:00:15Z    DEBUG   reconcile...    {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"cluster-sample","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample", "reconcileID": "2b218d55-32e0-4d09-b27a-2b2c9482cd00"}
2026-04-22T09:00:15Z    INFO    getting system users secret: cluster-sample     {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"cluster-sample","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample", "reconcileID": "2b218d55-32e0-4d09-b27a-2b2c9482cd00"}
2026-04-22T09:00:15Z    DEBUG   internal ACLs unchanged {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"cluster-sample","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample", "reconcileID": "2b218d55-32e0-4d09-b27a-2b2c9482cd00"}
2026-04-22T09:00:15Z    DEBUG   destination not yet visible to source via gossip; will retry    {"controller": "valkeycluster", "controllerGroup": "valkey.io", "controllerKind": "ValkeyCluster", "ValkeyCluster": {"name":"cluster-sample","namespace":"valkey-operator-system"}, "namespace": "valkey-operator-system", "name": "cluster-sample", "reconcileID": "2b218d55-32e0-4d09-b27a-2b2c9482cd00", "src": "10.244.0.30", "dst": "10.244.0.31", "dstId": "6513f34b99f908c4dfcb4b43741bc7c729f61c80"}
2026-04-22T09:00:15Z    DEBUG   events  Waiting for 10.244.0.30 to learn node 10.244.0.31       {"type": "Normal", "object": "nil", "action": "RebalanceSlots", "reason": "SlotsRebalancePending"}
```

If these use cases are not yet supported, that's fine - maybe we can raise Issues for these to be able to support them in future?

**Comment by daanvinken** [comment]
Thanks for testing! Seemingly these are pre-existing scale-up issues. This PR only changes the initial slot assignment for a 1-shard-0-replica cluster.

Both cases seem to get stuck in the gossip-waiting loops (before reaching any code this PR touches):
- Case 1: stuck at [`replica does not yet know primary (gossip pending)`](https://github.com/valkey-io/valkey-operator/blob/main/internal/controller/valkeycluster_controller.go#L839) - this is in the replication setup phase
- Case 2: stuck at [`destination not yet visible to source via gossip`](https://github.com/valkey-io/valkey-operator/blob/main/internal/controller/valkeycluster_controller.go#L984) - this is in the rebalancing phase

These would likely reproduce when scaling any cluster configuration, not just single-node origins. I will open issue(s) for both after some investigation 👍

**Comment by daanvinken** [comment]
I think we should add scaling E2E tests as well, I'll have a look.

**Comment by jdheyburn** [comment]
@daanvinken Are those E2E tests to be included in this PR?

**Comment by daanvinken** [comment]
The fix was fairly trivial, I added it here: https://github.com/valkey-io/valkey-operator/pull/147

E2E for all cases of this PR and the cases you mentioned are in https://github.com/valkey-io/valkey-operator/pull/148

**Review by jdheyburn — APPROVED** [review]
Thank you!
